// Generated by gencpp from file msg/RCLocal.msg
// DO NOT EDIT!


#ifndef MSG_MESSAGE_RCLOCAL_H
#define MSG_MESSAGE_RCLOCAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg
{
template <class ContainerAllocator>
struct RCLocal_
{
  typedef RCLocal_<ContainerAllocator> Type;

  RCLocal_()
    : steering(0)
    , drive(0)
    , status(false)  {
    }
  RCLocal_(const ContainerAllocator& _alloc)
    : steering(0)
    , drive(0)
    , status(false)  {
  (void)_alloc;
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _drive_type;
  _drive_type drive;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::msg::RCLocal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg::RCLocal_<ContainerAllocator> const> ConstPtr;

}; // struct RCLocal_

typedef ::msg::RCLocal_<std::allocator<void> > RCLocal;

typedef boost::shared_ptr< ::msg::RCLocal > RCLocalPtr;
typedef boost::shared_ptr< ::msg::RCLocal const> RCLocalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg::RCLocal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg::RCLocal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msg': ['/home/pi/gopigo3_ws/src/msg/msg'], 'std_msgs': ['/home/pi/ros_catkin_ws/build/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg::RCLocal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg::RCLocal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::RCLocal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::RCLocal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::RCLocal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::RCLocal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg::RCLocal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aad865e688304e7732de05868a861e8e";
  }

  static const char* value(const ::msg::RCLocal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaad865e688304e77ULL;
  static const uint64_t static_value2 = 0x32de05868a861e8eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg::RCLocal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg/RCLocal";
  }

  static const char* value(const ::msg::RCLocal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg::RCLocal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n\
int16 drive\n\
bool status\n\
\n\
\n\
";
  }

  static const char* value(const ::msg::RCLocal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg::RCLocal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.drive);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RCLocal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg::RCLocal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg::RCLocal_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "drive: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drive);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_MESSAGE_RCLOCAL_H
