set(_CATKIN_CURRENT_PACKAGE "rc_rover_node")
set(rc_rover_node_VERSION "0.0.0")
set(rc_rover_node_MAINTAINER "pi <pi@todo.todo>")
set(rc_rover_node_PACKAGE_FORMAT "2")
set(rc_rover_node_BUILD_DEPENDS "geometry_msgs" "rospy")
set(rc_rover_node_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy")
set(rc_rover_node_BUILDTOOL_DEPENDS "catkin")
set(rc_rover_node_BUILDTOOL_EXPORT_DEPENDS )
set(rc_rover_node_EXEC_DEPENDS "geometry_msgs" "rospy")
set(rc_rover_node_RUN_DEPENDS "geometry_msgs" "rospy")
set(rc_rover_node_TEST_DEPENDS )
set(rc_rover_node_DOC_DEPENDS )
set(rc_rover_node_URL_WEBSITE "")
set(rc_rover_node_URL_BUGTRACKER "")
set(rc_rover_node_URL_REPOSITORY "")
set(rc_rover_node_DEPRECATED "")