// Generated by gencpp from file local_controller_node/RControllerCommands.msg
// DO NOT EDIT!


#ifndef LOCAL_CONTROLLER_NODE_MESSAGE_RCONTROLLERCOMMANDS_H
#define LOCAL_CONTROLLER_NODE_MESSAGE_RCONTROLLERCOMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_controller_node
{
template <class ContainerAllocator>
struct RControllerCommands_
{
  typedef RControllerCommands_<ContainerAllocator> Type;

  RControllerCommands_()
    : steering(0)
    , drive(0)
    , status(false)  {
    }
  RControllerCommands_(const ContainerAllocator& _alloc)
    : steering(0)
    , drive(0)
    , status(false)  {
  (void)_alloc;
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _drive_type;
  _drive_type drive;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::local_controller_node::RControllerCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_controller_node::RControllerCommands_<ContainerAllocator> const> ConstPtr;

}; // struct RControllerCommands_

typedef ::local_controller_node::RControllerCommands_<std::allocator<void> > RControllerCommands;

typedef boost::shared_ptr< ::local_controller_node::RControllerCommands > RControllerCommandsPtr;
typedef boost::shared_ptr< ::local_controller_node::RControllerCommands const> RControllerCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_controller_node::RControllerCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_controller_node::RControllerCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace local_controller_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'local_controller_node': ['/home/pi/gopigo3_ws/src/local_controller_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_controller_node::RControllerCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_controller_node::RControllerCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_controller_node::RControllerCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aad865e688304e7732de05868a861e8e";
  }

  static const char* value(const ::local_controller_node::RControllerCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaad865e688304e77ULL;
  static const uint64_t static_value2 = 0x32de05868a861e8eULL;
};

template<class ContainerAllocator>
struct DataType< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_controller_node/RControllerCommands";
  }

  static const char* value(const ::local_controller_node::RControllerCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n\
int16 drive\n\
bool status\n\
";
  }

  static const char* value(const ::local_controller_node::RControllerCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.drive);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RControllerCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_controller_node::RControllerCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_controller_node::RControllerCommands_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "drive: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drive);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_CONTROLLER_NODE_MESSAGE_RCONTROLLERCOMMANDS_H
